### ISSUE TITLE
Feature Request: Add support for properties

### ISSUE THREAD

**Issue by BigBoot** [31/GodotOnReady#22]
Would be useful for example for AnimationTree, something like this:

```csharp
[OnReadyGet("AnimationTree", Property = "parameters/playback")]
private AnimationNodeStateMachinePlayback _playback;
```

Please tell me what you think, if you wan't I can also have a go at implementing this and submitting a PR.

**Comment by 31** [comment]
Nice idea, I like it a lot! I definitely have `_playback = (AnimationNodeStateMachinePlayback)_animator.Get("parameters/playback");` in a few ready methods, myself. 😄

A couple implementation details that jump to mind:
* If there are a bunch of `OnReadyGet`s pointing at various properties of the same target, the generated method should only call `GetNode` once.
  * This value should also be shared with an `OnReadyGet` that has no `Property`, if one exists.
  * But, this is a pretty minor optimization that I would be fine not having, if that makes it easier to implement. (It doesn't affect the `_playback` example at all.)
* Playing nicely with `OrNull` would be nice.

I would definitely be interested in taking a PR. 🙂 If that doesn't work out, I'll take a look at it next time I run into a place this would be useful for me.
