### ISSUE TITLE
OnReady/OnReadyGet not triggering in CI builds causing strange erorrs

### ISSUE THREAD

**Issue by TheOrioli** [31/GodotOnReady#28]
I'm writing this issue so others can find the solution easier. Potentially a similar text could be included in the README.md

When making builds inside docker images they sometimes don't include .NET by default  (e.g. https://github.com/abarichello/godot-ci/issues/80), but Godot still resolves NuGet packages. This causes the build pipeline to succeed, as all the code is valid, but the actual build will exhibit strange behavior as methods are not called and nodes are not fetched. 

The solution, if using a docker image based on Debian 10, is to add
```bash
wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb
apt-get update -qq
apt-get install -y apt-transport-https
apt-get update -qq
apt-get install -y dotnet-sdk-6.0
```
to your build pipeline before running the build command.

**Comment by 31** [comment]
I had a troubleshooting section that *kind of* mentions this (that you need the .NET SDK, not something else), but yeah, I've mainly focused on non-CI. I've added some more to the section (and revamped it a bit), and I linked https://github.com/abarichello/godot-ci/issues/80 as an example: https://github.com/31/GodotOnReady#i-dont-have-a-error-message-but-it-isnt-working. Thanks for letting me know, hopefully it helps someone in the future. 😄
