### ISSUE TITLE
#bug Incompatible with .NET Standard 2.0 or 2.1

### ISSUE THREAD

**Issue by MadFlyFish** [31/GodotOnReady#40]
Using .NET Standard 2.0 or 2.1 will lead to an exporting error.
But .Net framework 4.7.2 or 4.8 work just fine.
godot mono 3.5 beta4
![Y JI 7REAB)~(D{(RG%%)E5](https://user-images.githubusercontent.com/36298330/167333326-a0f7f78b-f9bb-472b-ba33-87b13c281f23.png)
![image](https://user-images.githubusercontent.com/36298330/167333627-e4ba4b02-c387-4401-b605-3863bd58924e.png)

**Comment by 31** [comment]
Godot Mono has an active bug where it doesn't include dependencies correctly by default with `netstandard2.0` and `netstandard2.1` target frameworks:

* https://github.com/godotengine/godot/issues/42271

The workaround is to add <`CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to your project.

For example, this project file uses `netstandard2.1` but doesn't reproduce the issue for me:

```xml
<Project Sdk="Godot.NET.Sdk/3.3.0">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GodotOnReady" Version="1.2.0" />
  </ItemGroup>

</Project>
```

If I remove `CopyLocalLockFileAssemblies` and try to export again, it reproduces the issue you saw.

Can you confirm whether this workaround works for you? There isn't anything I can realistically do about it on the library side.

**Comment by MadFlyFish** [comment]
> Godot Mono has an active bug where it doesn't include dependencies correctly by default with `netstandard2.0` and `netstandard2.1` target frameworks:
> 
> * [TargetFramework .NET Standard 2.0+ crashes on launch, can't find assembly System.Text.Json godotengine/godot#42271](https://github.com/godotengine/godot/issues/42271)
> 
> The workaround is to add <`CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to your project.
> 
> For example, this project file uses `netstandard2.1` but doesn't reproduce the issue for me:
> 
> ```
> <Project Sdk="Godot.NET.Sdk/3.3.0">
> 
>   <PropertyGroup>
>     <TargetFramework>netstandard2.1</TargetFramework>
>     <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="GodotOnReady" Version="1.2.0" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> If I remove `CopyLocalLockFileAssemblies` and try to export again, it reproduces the issue you saw.
> 
> Can you confirm whether this workaround works for you? There isn't anything I can realistically do about it on the library side.

Thanks a lot . It works now , as I do as you said. Great

**Comment by 31** [comment]
Wonderful, thanks for confirming!
