### ISSUE TITLE
A member named '_Ready' with the same parameter type has already been defined

### ISSUE THREAD

**Issue by Lsy-291** [31/GodotOnReady#44]
Hello, I encountered the following problems when using the godotonready you wrote. A member with the same parameter type named "_Ready" has been defined. This problem is related to the troubleshooting you listed, but I did not understand how to change my code. Could you please tell me in detail, thank you

Here is my code
`public override void _Ready()`

**Comment by Lsy-291** [comment]
Elsewhere, someone helped me point out the problem. Now it has been solved. You just need to change it to the following code
`[OnReady] public void YourFuncName()`
And finally, thanks to the author！

**Comment by 31** [comment]
Ah, thanks for letting me know about this part being unclear--I should definitely add a direct example fix there.

**Comment by 31** [comment]
Simplified that section a bit and added an example. (I tend to use `[OnReady] private void Ready()` when I'm swapping over existing scripts that do random stuff in `_Ready` and I'm not feeling creative about the name.)

Thanks again. 🙂
