### ISSUE TITLE
"_hasBeenSet" private bool should not be generated if unused

### ISSUE THREAD

**Issue by BenediktMagnus** [31/GodotOnReady#52]
Currently, for an `OnReadyGet` like this:
```csharp
[OnReadyGet(Export = true)]
private Texture MyTexture { get; set; } = null!;
```
the generated code looks like that:
```csharp
[Export] public global::Godot.Texture MyTextureResource
{
    get => MyTexture;
    set { _hasBeenSetMyTexture = true; MyTexture = value; }
}
private bool _hasBeenSetMyTexture;
```

<br>

The code responsible for that is this here:
https://github.com/31/GodotOnReady/blob/f1a47c01bedb9b275daf78543e21735844895deb/src/GodotOnReady.Generator/Additions/OnReadyGetResourceAddition.cs#L21-L27

But `_hasBeenSetMyTexture` is never used. (I noticed this because I got several CS0414 warnings when compiling.)
It would only be used if the generator had to generate the assignment by itself as in here:
https://github.com/31/GodotOnReady/blob/f1a47c01bedb9b275daf78543e21735844895deb/src/GodotOnReady.Generator/Additions/OnReadyGetResourceAddition.cs#L48-L55

<br>

I couldn't find any documentation regarding the possible usage of `_hasBeenSet` outside the generated code (i.e. by the user) and cannot imagine a sensible use case.
Therefore I suggest to only generate `_hasBeenSet` if `IsGeneratingAssignment` is set, so that it is only generated if it is actually used.

**Comment by 31** [comment]
`Export = true` made me realize this doc has a typo: `If true, always generates a property with [Export], even if Path isn't set.`. "Isn't" should be "is". 😞 This pairs with the constructor/Path doc which is the accurate side:

```cs
		/// <param name="path">
		/// The path that will be loaded when the node is ready. If not set, a property is generated
		/// with [Export], so the path can be set in the Godot editor.
		/// </param>
```

**Comment by 31** [comment]
Version 1.2.4 is now pushed with these changes. Thanks again! 😄
